# yaml-language-server: $schema=https://raw.githubusercontent.com/hvuhsg/gatego/refs/heads/main/config-schema.json

version: '0.0.1'
host: localhost
port: 8004

# open_telemetry:
#   endpoint: "localhost:4317"
#   sample_ratio: 1

services:
  - domain: localhost
    
    anomaly_detection: 
      active: true
    
    endpoints:
      - path: /
        # directory: /home/yoyo/  # Instead of destination
        destination: http://127.0.0.1:4007/
        # backend:
        #   balance_policy: 'least-latency'  # Can be 'round-robin', 'random', or 'least-latency'
        #   servers:
        #     - url: http://127.0.0.1:4007/
        #       weight: 1
        #     - url: http://127.0.0.1:4008/
        #       weight: 2
        
        minify: [js, html, css, json, xml, svg]

        gzip: true
        
        timeout: 3s  # Default (30s)
        max_size: 1024  # Default (10MB)

        ratelimits:
          - ip-60/m  # Limit requests from the same IP to 6 requests per minute.
          - ip-100/d

        openapi: openapi.yaml

        checks:
          - name: "DB Health"
            cron: "* * * * *"
            method: GET
            url: "http://127.0.0.1:4007/check_db"
            timeout: 5s
            headers:
              Host: domain.org
              Authorization: "Bearer abc123"
            on_failure: |
              echo Health check '$check_name' failed at $date with error: $error
        
        omit_headers: [Authorization, X-API-Key, X-Secret-Token]

        cache: true
