# yaml-language-server: $schema=https://raw.githubusercontent.com/hvuhsg/gatego/refs/heads/main/config-schema.json

version: '0.0.1'
host: 127.0.0.1
port: 8004

services:
  - domain: localho.st
    endpoints:
      - path: /
        # directory: /home/yoyo/  # Instead of destination
        # destination: http://127.0.0.1:4007/
        backend:
          balance_policy: 'least-latancy'  # Can be 'round-robin', 'random', or 'least-latancy'
          servers:
            - url: http://127.0.0.1:4007/
              weight: 1
            - url: http://127.0.0.1:4008/
              weight: 2
        
        minify: [js, html, css, json, xml, svg]

        gzip: true
        
        timeout: 3s  # Default (30s)
        max_size: 1024  # Default (10MB)

        ratelimits:
          - ip-60/m  # Limit requests from the same IP to 6 requests per minute.
          - ip-100/d

        openapi: openapi.yaml
